// https://gist.github.com/incredimike/1469814
export const COUNTRIES = {
    af: 'Afghanistan',
    al: 'Albania',
    dz: 'Algeria',
    as: 'American Samoa',
    ad: 'Andorra',
    ao: 'Angola',
    ai: 'Anguilla',
    aq: 'Antarctica',
    ag: 'Antigua and Barbuda',
    ar: 'Argentina',
    am: 'Armenia',
    aw: 'Aruba',
    au: 'Australia',
    at: 'Austria',
    az: 'Azerbaijan',
    bs: 'Bahamas (the)',
    bh: 'Bahrain',
    bd: 'Bangladesh',
    bb: 'Barbados',
    by: 'Belarus',
    be: 'Belgium',
    bz: 'Belize',
    bj: 'Benin',
    bm: 'Bermuda',
    bt: 'Bhutan',
    bo: 'Bolivia (Plurinational State of)',
    bq: 'Bonaire, Sint Eustatius and Saba',
    ba: 'Bosnia and Herzegovina',
    bw: 'Botswana',
    bv: 'Bouvet Island',
    br: 'Brazil',
    io: 'British Indian Ocean Territory (the)',
    bn: 'Brunei Darussalam',
    bg: 'Bulgaria',
    bf: 'Burkina Faso',
    bi: 'Burundi',
    cv: 'Cabo Verde',
    kh: 'Cambodia',
    cm: 'Cameroon',
    ca: 'Canada',
    ky: 'Cayman Islands (the)',
    cf: 'Central African Republic (the)',
    td: 'Chad',
    cl: 'Chile',
    cn: 'China',
    cx: 'Christmas Island',
    cc: 'Cocos (Keeling) Islands (the)',
    co: 'Colombia',
    km: 'Comoros (the)',
    cd: 'Congo (the Democratic Republic of the)',
    cg: 'Congo (the)',
    ck: 'Cook Islands (the)',
    cr: 'Costa Rica',
    hr: 'Croatia',
    cu: 'Cuba',
    cw: 'Curaçao',
    cy: 'Cyprus',
    cz: 'Czechia',
    ci: "Côte d'Ivoire",
    dk: 'Denmark',
    dj: 'Djibouti',
    dm: 'Dominica',
    do: 'Dominican Republic (the)',
    ec: 'Ecuador',
    eg: 'Egypt',
    sv: 'El Salvador',
    gq: 'Equatorial Guinea',
    er: 'Eritrea',
    ee: 'Estonia',
    sz: 'Eswatini',
    et: 'Ethiopia',
    fk: 'Falkland Islands (the) [Malvinas]',
    fo: 'Faroe Islands (the)',
    fj: 'Fiji',
    fi: 'Finland',
    fr: 'France',
    gf: 'French Guiana',
    pf: 'French Polynesia',
    tf: 'French Southern Territories (the)',
    ga: 'Gabon',
    gm: 'Gambia (the)',
    ge: 'Georgia',
    de: 'Germany',
    gh: 'Ghana',
    gi: 'Gibraltar',
    gr: 'Greece',
    gl: 'Greenland',
    gd: 'Grenada',
    gp: 'Guadeloupe',
    gu: 'Guam',
    gt: 'Guatemala',
    gg: 'Guernsey',
    gn: 'Guinea',
    gw: 'Guinea-Bissau',
    gy: 'Guyana',
    ht: 'Haiti',
    hm: 'Heard Island and McDonald Islands',
    va: 'Holy See (the)',
    hn: 'Honduras',
    hk: 'Hong Kong',
    hu: 'Hungary',
    is: 'Iceland',
    in: 'India',
    id: 'Indonesia',
    ir: 'Iran (Islamic Republic of)',
    iq: 'Iraq',
    ie: 'Ireland',
    im: 'Isle of Man',
    il: 'Israel',
    it: 'Italy',
    jm: 'Jamaica',
    jp: 'Japan',
    je: 'Jersey',
    jo: 'Jordan',
    kz: 'Kazakhstan',
    ke: 'Kenya',
    ki: 'Kiribati',
    kp: "Korea (the Democratic People's Republic of)",
    kr: 'Korea (the Republic of)',
    kw: 'Kuwait',
    kg: 'Kyrgyzstan',
    la: "Lao People's Democratic Republic (the)",
    lv: 'Latvia',
    lb: 'Lebanon',
    ls: 'Lesotho',
    lr: 'Liberia',
    ly: 'Libya',
    li: 'Liechtenstein',
    lt: 'Lithuania',
    lu: 'Luxembourg',
    mo: 'Macao',
    mg: 'Madagascar',
    mw: 'Malawi',
    my: 'Malaysia',
    mv: 'Maldives',
    ml: 'Mali',
    mt: 'Malta',
    mh: 'Marshall Islands (the)',
    mq: 'Martinique',
    mr: 'Mauritania',
    mu: 'Mauritius',
    yt: 'Mayotte',
    mx: 'Mexico',
    fm: 'Micronesia (Federated States of)',
    md: 'Moldova (the Republic of)',
    mc: 'Monaco',
    mn: 'Mongolia',
    me: 'Montenegro',
    ms: 'Montserrat',
    ma: 'Morocco',
    mz: 'Mozambique',
    mm: 'Myanmar',
    na: 'Namibia',
    nr: 'Nauru',
    np: 'Nepal',
    nl: 'Netherlands (the)',
    nc: 'New Caledonia',
    nz: 'New Zealand',
    ni: 'Nicaragua',
    ne: 'Niger (the)',
    ng: 'Nigeria',
    nu: 'Niue',
    nf: 'Norfolk Island',
    mp: 'Northern Mariana Islands (the)',
    no: 'Norway',
    om: 'Oman',
    pk: 'Pakistan',
    pw: 'Palau',
    ps: 'Palestine, State of',
    pa: 'Panama',
    pg: 'Papua New Guinea',
    py: 'Paraguay',
    pe: 'Peru',
    ph: 'Philippines (the)',
    pn: 'Pitcairn',
    pl: 'Poland',
    pt: 'Portugal',
    pr: 'Puerto Rico',
    qa: 'Qatar',
    mk: 'Republic of North Macedonia',
    ro: 'Romania',
    ru: 'Russian Federation (the)',
    rw: 'Rwanda',
    re: 'Réunion',
    bl: 'Saint Barthélemy',
    sh: 'Saint Helena, Ascension and Tristan da Cunha',
    kn: 'Saint Kitts and Nevis',
    lc: 'Saint Lucia',
    mf: 'Saint Martin (French part)',
    pm: 'Saint Pierre and Miquelon',
    vc: 'Saint Vincent and the Grenadines',
    ws: 'Samoa',
    sm: 'San Marino',
    st: 'Sao Tome and Principe',
    sa: 'Saudi Arabia',
    sn: 'Senegal',
    rs: 'Serbia',
    sc: 'Seychelles',
    sl: 'Sierra Leone',
    sg: 'Singapore',
    sx: 'Sint Maarten (Dutch part)',
    sk: 'Slovakia',
    si: 'Slovenia',
    sb: 'Solomon Islands',
    so: 'Somalia',
    za: 'South Africa',
    gs: 'South Georgia and the South Sandwich Islands',
    ss: 'South Sudan',
    es: 'Spain',
    lk: 'Sri Lanka',
    sd: 'Sudan (the)',
    sr: 'Suriname',
    sj: 'Svalbard and Jan Mayen',
    se: 'Sweden',
    ch: 'Switzerland',
    sy: 'Syrian Arab Republic',
    tw: 'Taiwan',
    tj: 'Tajikistan',
    tz: 'Tanzania, United Republic of',
    th: 'Thailand',
    tl: 'Timor-Leste',
    tg: 'Togo',
    tk: 'Tokelau',
    to: 'Tonga',
    tt: 'Trinidad and Tobago',
    tn: 'Tunisia',
    tr: 'Turkey',
    tm: 'Turkmenistan',
    tc: 'Turks and Caicos Islands (the)',
    tv: 'Tuvalu',
    ug: 'Uganda',
    ua: 'Ukraine',
    ae: 'United Arab Emirates (the)',
    gb: 'United Kingdom',
    um: 'United States Minor Outlying Islands (the)',
    us: 'United States',
    uy: 'Uruguay',
    uz: 'Uzbekistan',
    vu: 'Vanuatu',
    ve: 'Venezuela (Bolivarian Republic of)',
    vn: 'Viet Nam',
    vg: 'Virgin Islands (British)',
    vi: 'Virgin Islands (U.S.)',
    wf: 'Wallis and Futuna',
    eh: 'Western Sahara',
    ye: 'Yemen',
    zm: 'Zambia',
    zw: 'Zimbabwe',
    ax: 'Åland Islands',
} as const;

// https://www.html-code-generator.com/javascript/json/currency-name
export const CURRENCIES = {
    AFA: 'Afghan Afghani',
    ALL: 'Albanian Lek',
    DZD: 'Algerian Dinar',
    AOA: 'Angolan Kwanza',
    ARS: 'Argentine Peso',
    AMD: 'Armenian Dram',
    AWG: 'Aruban Florin',
    AUD: 'Australian Dollar',
    AZN: 'Azerbaijani Manat',
    BSD: 'Bahamian Dollar',
    BHD: 'Bahraini Dinar',
    BDT: 'Bangladeshi Taka',
    BBD: 'Barbadian Dollar',
    BYR: 'Belarusian Ruble',
    BEF: 'Belgian Franc',
    BZD: 'Belize Dollar',
    BMD: 'Bermudan Dollar',
    BTN: 'Bhutanese Ngultrum',
    BTC: 'Bitcoin',
    BOB: 'Bolivian Boliviano',
    BAM: 'Bosnia-Herzegovina Convertible Mark',
    BWP: 'Botswanan Pula',
    BRL: 'Brazilian Real',
    GBP: 'British Pound Sterling',
    BND: 'Brunei Dollar',
    BGN: 'Bulgarian Lev',
    BIF: 'Burundian Franc',
    KHR: 'Cambodian Riel',
    CAD: 'Canadian Dollar',
    CVE: 'Cape Verdean Escudo',
    KYD: 'Cayman Islands Dollar',
    XOF: 'CFA Franc BCEAO',
    XAF: 'CFA Franc BEAC',
    XPF: 'CFP Franc',
    CLP: 'Chilean Peso',
    CNY: 'Chinese Yuan',
    COP: 'Colombian Peso',
    KMF: 'Comorian Franc',
    CDF: 'Congolese Franc',
    CRC: 'Costa Rican ColÃ³n',
    HRK: 'Croatian Kuna',
    CUC: 'Cuban Convertible Peso',
    CZK: 'Czech Republic Koruna',
    DKK: 'Danish Krone',
    DJF: 'Djiboutian Franc',
    DOP: 'Dominican Peso',
    XCD: 'East Caribbean Dollar',
    EGP: 'Egyptian Pound',
    ERN: 'Eritrean Nakfa',
    EEK: 'Estonian Kroon',
    ETB: 'Ethiopian Birr',
    EUR: 'Euro',
    FKP: 'Falkland Islands Pound',
    FJD: 'Fijian Dollar',
    GMD: 'Gambian Dalasi',
    GEL: 'Georgian Lari',
    DEM: 'German Mark',
    GHS: 'Ghanaian Cedi',
    GIP: 'Gibraltar Pound',
    GRD: 'Greek Drachma',
    GTQ: 'Guatemalan Quetzal',
    GNF: 'Guinean Franc',
    GYD: 'Guyanaese Dollar',
    HTG: 'Haitian Gourde',
    HNL: 'Honduran Lempira',
    HKD: 'Hong Kong Dollar',
    HUF: 'Hungarian Forint',
    ISK: 'Icelandic KrÃ³na',
    INR: 'Indian Rupee',
    IDR: 'Indonesian Rupiah',
    IRR: 'Iranian Rial',
    IQD: 'Iraqi Dinar',
    ILS: 'Israeli New Sheqel',
    ITL: 'Italian Lira',
    JMD: 'Jamaican Dollar',
    JPY: 'Japanese Yen',
    JOD: 'Jordanian Dinar',
    KZT: 'Kazakhstani Tenge',
    KES: 'Kenyan Shilling',
    KWD: 'Kuwaiti Dinar',
    KGS: 'Kyrgystani Som',
    LAK: 'Laotian Kip',
    LVL: 'Latvian Lats',
    LBP: 'Lebanese Pound',
    LSL: 'Lesotho Loti',
    LRD: 'Liberian Dollar',
    LYD: 'Libyan Dinar',
    LTL: 'Lithuanian Litas',
    MOP: 'Macanese Pataca',
    MKD: 'Macedonian Denar',
    MGA: 'Malagasy Ariary',
    MWK: 'Malawian Kwacha',
    MYR: 'Malaysian Ringgit',
    MVR: 'Maldivian Rufiyaa',
    MRO: 'Mauritanian Ouguiya',
    MUR: 'Mauritian Rupee',
    MXN: 'Mexican Peso',
    MDL: 'Moldovan Leu',
    MNT: 'Mongolian Tugrik',
    MAD: 'Moroccan Dirham',
    MZM: 'Mozambican Metical',
    MMK: 'Myanmar Kyat',
    NAD: 'Namibian Dollar',
    NPR: 'Nepalese Rupee',
    ANG: 'Netherlands Antillean Guilder',
    TWD: 'New Taiwan Dollar',
    NZD: 'New Zealand Dollar',
    NIO: 'Nicaraguan CÃ³rdoba',
    NGN: 'Nigerian Naira',
    KPW: 'North Korean Won',
    NOK: 'Norwegian Krone',
    OMR: 'Omani Rial',
    PKR: 'Pakistani Rupee',
    PAB: 'Panamanian Balboa',
    PGK: 'Papua New Guinean Kina',
    PYG: 'Paraguayan Guarani',
    PEN: 'Peruvian Nuevo Sol',
    PHP: 'Philippine Peso',
    PLN: 'Polish Zloty',
    QAR: 'Qatari Rial',
    RON: 'Romanian Leu',
    RUB: 'Russian Ruble',
    RWF: 'Rwandan Franc',
    SVC: 'Salvadoran ColÃ³n',
    WST: 'Samoan Tala',
    SAR: 'Saudi Riyal',
    RSD: 'Serbian Dinar',
    SCR: 'Seychellois Rupee',
    SLL: 'Sierra Leonean Leone',
    SGD: 'Singapore Dollar',
    SKK: 'Slovak Koruna',
    SBD: 'Solomon Islands Dollar',
    SOS: 'Somali Shilling',
    ZAR: 'South African Rand',
    KRW: 'South Korean Won',
    XDR: 'Special Drawing Rights',
    LKR: 'Sri Lankan Rupee',
    SHP: 'St. Helena Pound',
    SDG: 'Sudanese Pound',
    SRD: 'Surinamese Dollar',
    SZL: 'Swazi Lilangeni',
    SEK: 'Swedish Krona',
    CHF: 'Swiss Franc',
    SYP: 'Syrian Pound',
    STD: 'São Tomé and Príncipe Dobra',
    TJS: 'Tajikistani Somoni',
    TZS: 'Tanzanian Shilling',
    THB: 'Thai Baht',
    TOP: "Tongan Pa'anga",
    TTD: 'Trinidad & Tobago Dollar',
    TND: 'Tunisian Dinar',
    TRY: 'Turkish Lira',
    TMT: 'Turkmenistani Manat',
    UGX: 'Ugandan Shilling',
    UAH: 'Ukrainian Hryvnia',
    AED: 'United Arab Emirates Dirham',
    UYU: 'Uruguayan Peso',
    USD: 'US Dollar',
    UZS: 'Uzbekistan Som',
    VUV: 'Vanuatu Vatu',
    VEF: 'Venezuelan BolÃvar',
    VND: 'Vietnamese Dong',
    YER: 'Yemeni Rial',
    ZMK: 'Zambian Kwacha',
} as const;
