// https://github.com/matiassingers/emoji-flags/blob/master/data.json
export const COUNTRIES = {
    AD: {code: 'AD', emoji: '🇦🇩', name: 'Andorra'},
    AE: {code: 'AE', emoji: '🇦🇪', name: 'United Arab Emirates'},
    AF: {code: 'AF', emoji: '🇦🇫', name: 'Afghanistan'},
    AG: {code: 'AG', emoji: '🇦🇬', name: 'Antigua and Barbuda'},
    AI: {code: 'AI', emoji: '🇦🇮', name: 'Anguilla'},
    AL: {code: 'AL', emoji: '🇦🇱', name: 'Albania'},
    AM: {code: 'AM', emoji: '🇦🇲', name: 'Armenia'},
    AO: {code: 'AO', emoji: '🇦🇴', name: 'Angola'},
    AQ: {code: 'AQ', emoji: '🇦🇶', name: 'Antarctica'},
    AR: {code: 'AR', emoji: '🇦🇷', name: 'Argentina'},
    AS: {code: 'AS', emoji: '🇦🇸', name: 'American Samoa'},
    AT: {code: 'AT', emoji: '🇦🇹', name: 'Austria'},
    AU: {code: 'AU', emoji: '🇦🇺', name: 'Australia'},
    AW: {code: 'AW', emoji: '🇦🇼', name: 'Aruba'},
    AX: {code: 'AX', emoji: '🇦🇽', name: 'Åland Islands'},
    AZ: {code: 'AZ', emoji: '🇦🇿', name: 'Azerbaijan'},
    BA: {code: 'BA', emoji: '🇧🇦', name: 'Bosnia and Herzegovina'},
    BB: {code: 'BB', emoji: '🇧🇧', name: 'Barbados'},
    BD: {code: 'BD', emoji: '🇧🇩', name: 'Bangladesh'},
    BE: {code: 'BE', emoji: '🇧🇪', name: 'Belgium'},
    BF: {code: 'BF', emoji: '🇧🇫', name: 'Burkina Faso'},
    BG: {code: 'BG', emoji: '🇧🇬', name: 'Bulgaria'},
    BH: {code: 'BH', emoji: '🇧🇭', name: 'Bahrain'},
    BI: {code: 'BI', emoji: '🇧🇮', name: 'Burundi'},
    BJ: {code: 'BJ', emoji: '🇧🇯', name: 'Benin'},
    BL: {code: 'BL', emoji: '🇧🇱', name: 'Saint Barthélemy'},
    BM: {code: 'BM', emoji: '🇧🇲', name: 'Bermuda'},
    BN: {code: 'BN', emoji: '🇧🇳', name: 'Brunei Darussalam'},
    BO: {code: 'BO', emoji: '🇧🇴', name: 'Bolivia'},
    BQ: {code: 'BQ', emoji: '🇧🇶', name: 'Bonaire, Sint Eustatius and Saba'},
    BR: {code: 'BR', emoji: '🇧🇷', name: 'Brazil'},
    BS: {code: 'BS', emoji: '🇧🇸', name: 'Bahamas'},
    BT: {code: 'BT', emoji: '🇧🇹', name: 'Bhutan'},
    BV: {code: 'BV', emoji: '🇧🇻', name: 'Bouvet Island'},
    BW: {code: 'BW', emoji: '🇧🇼', name: 'Botswana'},
    BY: {code: 'BY', emoji: '🇧🇾', name: 'Belarus'},
    BZ: {code: 'BZ', emoji: '🇧🇿', name: 'Belize'},
    CA: {code: 'CA', emoji: '🇨🇦', name: 'Canada'},
    CC: {code: 'CC', emoji: '🇨🇨', name: 'Cocos (Keeling) Islands'},
    CD: {code: 'CD', emoji: '🇨🇩', name: 'Congo'},
    CF: {code: 'CF', emoji: '🇨🇫', name: 'Central African Republic'},
    CG: {code: 'CG', emoji: '🇨🇬', name: 'Congo'},
    CH: {code: 'CH', emoji: '🇨🇭', name: 'Switzerland'},
    CI: {code: 'CI', emoji: '🇨🇮', name: "Côte D'Ivoire"},
    CK: {code: 'CK', emoji: '🇨🇰', name: 'Cook Islands'},
    CL: {code: 'CL', emoji: '🇨🇱', name: 'Chile'},
    CM: {code: 'CM', emoji: '🇨🇲', name: 'Cameroon'},
    CN: {code: 'CN', emoji: '🇨🇳', name: 'China'},
    CO: {code: 'CO', emoji: '🇨🇴', name: 'Colombia'},
    CR: {code: 'CR', emoji: '🇨🇷', name: 'Costa Rica'},
    CU: {code: 'CU', emoji: '🇨🇺', name: 'Cuba'},
    CV: {code: 'CV', emoji: '🇨🇻', name: 'Cape Verde'},
    CW: {code: 'CW', emoji: '🇨🇼', name: 'Curaçao'},
    CX: {code: 'CX', emoji: '🇨🇽', name: 'Christmas Island'},
    CY: {code: 'CY', emoji: '🇨🇾', name: 'Cyprus'},
    CZ: {code: 'CZ', emoji: '🇨🇿', name: 'Czech Republic'},
    DE: {code: 'DE', emoji: '🇩🇪', name: 'Germany'},
    DJ: {code: 'DJ', emoji: '🇩🇯', name: 'Djibouti'},
    DK: {code: 'DK', emoji: '🇩🇰', name: 'Denmark'},
    DM: {code: 'DM', emoji: '🇩🇲', name: 'Dominica'},
    DO: {code: 'DO', emoji: '🇩🇴', name: 'Dominican Republic'},
    DZ: {code: 'DZ', emoji: '🇩🇿', name: 'Algeria'},
    EC: {code: 'EC', emoji: '🇪🇨', name: 'Ecuador'},
    EE: {code: 'EE', emoji: '🇪🇪', name: 'Estonia'},
    EG: {code: 'EG', emoji: '🇪🇬', name: 'Egypt'},
    EH: {code: 'EH', emoji: '🇪🇭', name: 'Western Sahara'},
    ER: {code: 'ER', emoji: '🇪🇷', name: 'Eritrea'},
    ES: {code: 'ES', emoji: '🇪🇸', name: 'Spain'},
    ET: {code: 'ET', emoji: '🇪🇹', name: 'Ethiopia'},
    FI: {code: 'FI', emoji: '🇫🇮', name: 'Finland'},
    FJ: {code: 'FJ', emoji: '🇫🇯', name: 'Fiji'},
    FK: {code: 'FK', emoji: '🇫🇰', name: 'Falkland Islands (Malvinas)'},
    FM: {code: 'FM', emoji: '🇫🇲', name: 'Micronesia'},
    FO: {code: 'FO', emoji: '🇫🇴', name: 'Faroe Islands'},
    FR: {code: 'FR', emoji: '🇫🇷', name: 'France'},
    GA: {code: 'GA', emoji: '🇬🇦', name: 'Gabon'},
    GB: {code: 'GB', emoji: '🇬🇧', name: 'United Kingdom'},
    GD: {code: 'GD', emoji: '🇬🇩', name: 'Grenada'},
    GE: {code: 'GE', emoji: '🇬🇪', name: 'Georgia'},
    GF: {code: 'GF', emoji: '🇬🇫', name: 'French Guiana'},
    GG: {code: 'GG', emoji: '🇬🇬', name: 'Guernsey'},
    GH: {code: 'GH', emoji: '🇬🇭', name: 'Ghana'},
    GI: {code: 'GI', emoji: '🇬🇮', name: 'Gibraltar'},
    GL: {code: 'GL', emoji: '🇬🇱', name: 'Greenland'},
    GM: {code: 'GM', emoji: '🇬🇲', name: 'Gambia'},
    GN: {code: 'GN', emoji: '🇬🇳', name: 'Guinea'},
    GP: {code: 'GP', emoji: '🇬🇵', name: 'Guadeloupe'},
    GQ: {code: 'GQ', emoji: '🇬🇶', name: 'Equatorial Guinea'},
    GR: {code: 'GR', emoji: '🇬🇷', name: 'Greece'},
    GS: {code: 'GS', emoji: '🇬🇸', name: 'South Georgia'},
    GT: {code: 'GT', emoji: '🇬🇹', name: 'Guatemala'},
    GU: {code: 'GU', emoji: '🇬🇺', name: 'Guam'},
    GW: {code: 'GW', emoji: '🇬🇼', name: 'Guinea-Bissau'},
    GY: {code: 'GY', emoji: '🇬🇾', name: 'Guyana'},
    HK: {code: 'HK', emoji: '🇭🇰', name: 'Hong Kong'},
    HM: {code: 'HM', emoji: '🇭🇲', name: 'Heard Island and Mcdonald Islands'},
    HN: {code: 'HN', emoji: '🇭🇳', name: 'Honduras'},
    HR: {code: 'HR', emoji: '🇭🇷', name: 'Croatia'},
    HT: {code: 'HT', emoji: '🇭🇹', name: 'Haiti'},
    HU: {code: 'HU', emoji: '🇭🇺', name: 'Hungary'},
    ID: {code: 'ID', emoji: '🇮🇩', name: 'Indonesia'},
    IE: {code: 'IE', emoji: '🇮🇪', name: 'Ireland'},
    IL: {code: 'IL', emoji: '🇮🇱', name: 'Israel'},
    IM: {code: 'IM', emoji: '🇮🇲', name: 'Isle of Man'},
    IN: {code: 'IN', emoji: '🇮🇳', name: 'India'},
    IO: {code: 'IO', emoji: '🇮🇴', name: 'British Indian Ocean Territory'},
    IQ: {code: 'IQ', emoji: '🇮🇶', name: 'Iraq'},
    IR: {code: 'IR', emoji: '🇮🇷', name: 'Iran'},
    IS: {code: 'IS', emoji: '🇮🇸', name: 'Iceland'},
    IT: {code: 'IT', emoji: '🇮🇹', name: 'Italy'},
    JE: {code: 'JE', emoji: '🇯🇪', name: 'Jersey'},
    JM: {code: 'JM', emoji: '🇯🇲', name: 'Jamaica'},
    JO: {code: 'JO', emoji: '🇯🇴', name: 'Jordan'},
    JP: {code: 'JP', emoji: '🇯🇵', name: 'Japan'},
    KE: {code: 'KE', emoji: '🇰🇪', name: 'Kenya'},
    KG: {code: 'KG', emoji: '🇰🇬', name: 'Kyrgyzstan'},
    KH: {code: 'KH', emoji: '🇰🇭', name: 'Cambodia'},
    KI: {code: 'KI', emoji: '🇰🇮', name: 'Kiribati'},
    KM: {code: 'KM', emoji: '🇰🇲', name: 'Comoros'},
    KN: {code: 'KN', emoji: '🇰🇳', name: 'Saint Kitts and Nevis'},
    KP: {code: 'KP', emoji: '🇰🇵', name: 'North Korea'},
    KR: {code: 'KR', emoji: '🇰🇷', name: 'South Korea'},
    KW: {code: 'KW', emoji: '🇰🇼', name: 'Kuwait'},
    KY: {code: 'KY', emoji: '🇰🇾', name: 'Cayman Islands'},
    KZ: {code: 'KZ', emoji: '🇰🇿', name: 'Kazakhstan'},
    LA: {code: 'LA', emoji: '🇱🇦', name: "Lao People's Democratic Republic"},
    LB: {code: 'LB', emoji: '🇱🇧', name: 'Lebanon'},
    LC: {code: 'LC', emoji: '🇱🇨', name: 'Saint Lucia'},
    LI: {code: 'LI', emoji: '🇱🇮', name: 'Liechtenstein'},
    LK: {code: 'LK', emoji: '🇱🇰', name: 'Sri Lanka'},
    LR: {code: 'LR', emoji: '🇱🇷', name: 'Liberia'},
    LS: {code: 'LS', emoji: '🇱🇸', name: 'Lesotho'},
    LT: {code: 'LT', emoji: '🇱🇹', name: 'Lithuania'},
    LU: {code: 'LU', emoji: '🇱🇺', name: 'Luxembourg'},
    LV: {code: 'LV', emoji: '🇱🇻', name: 'Latvia'},
    LY: {code: 'LY', emoji: '🇱🇾', name: 'Libya'},
    MA: {code: 'MA', emoji: '🇲🇦', name: 'Morocco'},
    MC: {code: 'MC', emoji: '🇲🇨', name: 'Monaco'},
    MD: {code: 'MD', emoji: '🇲🇩', name: 'Moldova'},
    ME: {code: 'ME', emoji: '🇲🇪', name: 'Montenegro'},
    MF: {code: 'MF', emoji: '🇲🇫', name: 'Saint Martin (French Part)'},
    MG: {code: 'MG', emoji: '🇲🇬', name: 'Madagascar'},
    MH: {code: 'MH', emoji: '🇲🇭', name: 'Marshall Islands'},
    MK: {code: 'MK', emoji: '🇲🇰', name: 'Macedonia'},
    ML: {code: 'ML', emoji: '🇲🇱', name: 'Mali'},
    MM: {code: 'MM', emoji: '🇲🇲', name: 'Myanmar'},
    MN: {code: 'MN', emoji: '🇲🇳', name: 'Mongolia'},
    MO: {code: 'MO', emoji: '🇲🇴', name: 'Macao'},
    MP: {code: 'MP', emoji: '🇲🇵', name: 'Northern Mariana Islands'},
    MQ: {code: 'MQ', emoji: '🇲🇶', name: 'Martinique'},
    MR: {code: 'MR', emoji: '🇲🇷', name: 'Mauritania'},
    MS: {code: 'MS', emoji: '🇲🇸', name: 'Montserrat'},
    MT: {code: 'MT', emoji: '🇲🇹', name: 'Malta'},
    MU: {code: 'MU', emoji: '🇲🇺', name: 'Mauritius'},
    MV: {code: 'MV', emoji: '🇲🇻', name: 'Maldives'},
    MW: {code: 'MW', emoji: '🇲🇼', name: 'Malawi'},
    MX: {code: 'MX', emoji: '🇲🇽', name: 'Mexico'},
    MY: {code: 'MY', emoji: '🇲🇾', name: 'Malaysia'},
    MZ: {code: 'MZ', emoji: '🇲🇿', name: 'Mozambique'},
    NA: {code: 'NA', emoji: '🇳🇦', name: 'Namibia'},
    NC: {code: 'NC', emoji: '🇳🇨', name: 'New Caledonia'},
    NE: {code: 'NE', emoji: '🇳🇪', name: 'Niger'},
    NF: {code: 'NF', emoji: '🇳🇫', name: 'Norfolk Island'},
    NG: {code: 'NG', emoji: '🇳🇬', name: 'Nigeria'},
    NI: {code: 'NI', emoji: '🇳🇮', name: 'Nicaragua'},
    NL: {code: 'NL', emoji: '🇳🇱', name: 'Netherlands'},
    NO: {code: 'NO', emoji: '🇳🇴', name: 'Norway'},
    NP: {code: 'NP', emoji: '🇳🇵', name: 'Nepal'},
    NR: {code: 'NR', emoji: '🇳🇷', name: 'Nauru'},
    NU: {code: 'NU', emoji: '🇳🇺', name: 'Niue'},
    NZ: {code: 'NZ', emoji: '🇳🇿', name: 'New Zealand'},
    OM: {code: 'OM', emoji: '🇴🇲', name: 'Oman'},
    PA: {code: 'PA', emoji: '🇵🇦', name: 'Panama'},
    PE: {code: 'PE', emoji: '🇵🇪', name: 'Peru'},
    PF: {code: 'PF', emoji: '🇵🇫', name: 'French Polynesia'},
    PG: {code: 'PG', emoji: '🇵🇬', name: 'Papua New Guinea'},
    PH: {code: 'PH', emoji: '🇵🇭', name: 'Philippines'},
    PK: {code: 'PK', emoji: '🇵🇰', name: 'Pakistan'},
    PL: {code: 'PL', emoji: '🇵🇱', name: 'Poland'},
    PM: {code: 'PM', emoji: '🇵🇲', name: 'Saint Pierre and Miquelon'},
    PN: {code: 'PN', emoji: '🇵🇳', name: 'Pitcairn'},
    PR: {code: 'PR', emoji: '🇵🇷', name: 'Puerto Rico'},
    PS: {code: 'PS', emoji: '🇵🇸', name: 'Palestinian Territory'},
    PT: {code: 'PT', emoji: '🇵🇹', name: 'Portugal'},
    PW: {code: 'PW', emoji: '🇵🇼', name: 'Palau'},
    PY: {code: 'PY', emoji: '🇵🇾', name: 'Paraguay'},
    QA: {code: 'QA', emoji: '🇶🇦', name: 'Qatar'},
    RE: {code: 'RE', emoji: '🇷🇪', name: 'Réunion'},
    RO: {code: 'RO', emoji: '🇷🇴', name: 'Romania'},
    RS: {code: 'RS', emoji: '🇷🇸', name: 'Serbia'},
    RU: {code: 'RU', emoji: '🇷🇺', name: 'Russia'},
    RW: {code: 'RW', emoji: '🇷🇼', name: 'Rwanda'},
    SA: {code: 'SA', emoji: '🇸🇦', name: 'Saudi Arabia'},
    SB: {code: 'SB', emoji: '🇸🇧', name: 'Solomon Islands'},
    SC: {code: 'SC', emoji: '🇸🇨', name: 'Seychelles'},
    SD: {code: 'SD', emoji: '🇸🇩', name: 'Sudan'},
    SE: {code: 'SE', emoji: '🇸🇪', name: 'Sweden'},
    SG: {code: 'SG', emoji: '🇸🇬', name: 'Singapore'},
    SH: {
        code: 'SH',
        emoji: '🇸🇭',
        name: 'Saint Helena, Ascension and Tristan Da Cunha',
    },
    SI: {code: 'SI', emoji: '🇸🇮', name: 'Slovenia'},
    SJ: {code: 'SJ', emoji: '🇸🇯', name: 'Svalbard and Jan Mayen'},
    SK: {code: 'SK', emoji: '🇸🇰', name: 'Slovakia'},
    SL: {code: 'SL', emoji: '🇸🇱', name: 'Sierra Leone'},
    SM: {code: 'SM', emoji: '🇸🇲', name: 'San Marino'},
    SN: {code: 'SN', emoji: '🇸🇳', name: 'Senegal'},
    SO: {code: 'SO', emoji: '🇸🇴', name: 'Somalia'},
    SR: {code: 'SR', emoji: '🇸🇷', name: 'Suriname'},
    SS: {code: 'SS', emoji: '🇸🇸', name: 'South Sudan'},
    ST: {code: 'ST', emoji: '🇸🇹', name: 'Sao Tome and Principe'},
    SV: {code: 'SV', emoji: '🇸🇻', name: 'El Salvador'},
    SX: {code: 'SX', emoji: '🇸🇽', name: 'Sint Maarten (Dutch Part)'},
    SY: {code: 'SY', emoji: '🇸🇾', name: 'Syrian Arab Republic'},
    SZ: {code: 'SZ', emoji: '🇸🇿', name: 'Swaziland'},
    TC: {code: 'TC', emoji: '🇹🇨', name: 'Turks and Caicos Islands'},
    TD: {code: 'TD', emoji: '🇹🇩', name: 'Chad'},
    TF: {code: 'TF', emoji: '🇹🇫', name: 'French Southern Territories'},
    TG: {code: 'TG', emoji: '🇹🇬', name: 'Togo'},
    TH: {code: 'TH', emoji: '🇹🇭', name: 'Thailand'},
    TJ: {code: 'TJ', emoji: '🇹🇯', name: 'Tajikistan'},
    TK: {code: 'TK', emoji: '🇹🇰', name: 'Tokelau'},
    TL: {code: 'TL', emoji: '🇹🇱', name: 'Timor-Leste'},
    TM: {code: 'TM', emoji: '🇹🇲', name: 'Turkmenistan'},
    TN: {code: 'TN', emoji: '🇹🇳', name: 'Tunisia'},
    TO: {code: 'TO', emoji: '🇹🇴', name: 'Tonga'},
    TR: {code: 'TR', emoji: '🇹🇷', name: 'Turkey'},
    TT: {code: 'TT', emoji: '🇹🇹', name: 'Trinidad and Tobago'},
    TV: {code: 'TV', emoji: '🇹🇻', name: 'Tuvalu'},
    TW: {code: 'TW', emoji: '🇹🇼', name: 'Taiwan'},
    TZ: {code: 'TZ', emoji: '🇹🇿', name: 'Tanzania'},
    UA: {code: 'UA', emoji: '🇺🇦', name: 'Ukraine'},
    UG: {code: 'UG', emoji: '🇺🇬', name: 'Uganda'},
    UM: {code: 'UM', emoji: '🇺🇲', name: 'United States Minor Outlying Islands'},
    US: {code: 'US', emoji: '🇺🇸', name: 'United States'},
    UY: {code: 'UY', emoji: '🇺🇾', name: 'Uruguay'},
    UZ: {code: 'UZ', emoji: '🇺🇿', name: 'Uzbekistan'},
    VA: {code: 'VA', emoji: '🇻🇦', name: 'Vatican City'},
    VC: {code: 'VC', emoji: '🇻🇨', name: 'Saint Vincent and The Grenadines'},
    VE: {code: 'VE', emoji: '🇻🇪', name: 'Venezuela'},
    VG: {code: 'VG', emoji: '🇻🇬', name: 'Virgin Islands, British'},
    VI: {code: 'VI', emoji: '🇻🇮', name: 'Virgin Islands, U.S.'},
    VN: {code: 'VN', emoji: '🇻🇳', name: 'Viet Nam'},
    VU: {code: 'VU', emoji: '🇻🇺', name: 'Vanuatu'},
    WF: {code: 'WF', emoji: '🇼🇫', name: 'Wallis and Futuna'},
    WS: {code: 'WS', emoji: '🇼🇸', name: 'Samoa'},
    XK: {code: 'XK', emoji: '🇽🇰', name: 'Kosovo'},
    YE: {code: 'YE', emoji: '🇾🇪', name: 'Yemen'},
    YT: {code: 'YT', emoji: '🇾🇹', name: 'Mayotte'},
    ZA: {code: 'ZA', emoji: '🇿🇦', name: 'South Africa'},
    ZM: {code: 'ZM', emoji: '🇿🇲', name: 'Zambia'},
    ZW: {code: 'ZW', emoji: '🇿🇼', name: 'Zimbabwe'},
} as const;

// https://www.html-code-generator.com/javascript/json/currency-name
// length 164
export const CURRENCIES = {
    AUD: {
        name: 'Australian Dollar',
        symbol: '$',
        code: 'AUD',
        emoji: '🇦🇺',
    },
    GBP: {
        name: 'British Pound Sterling',
        symbol: '£',
        code: 'GBP',
        emoji: '🇬🇧',
    },
    CAD: {
        name: 'Canadian Dollar',
        symbol: '$',
        code: 'CAD',
        emoji: '🇨🇦',
    },
    EUR: {
        name: 'Euro',
        symbol: '€',
        code: 'EUR',
        emoji: '🇪🇺',
    },
    USD: {
        name: 'US Dollar',
        symbol: '$',
        code: 'USD',
        emoji: '🇺🇸',
    },
    TEST: {
        name: 'TEST',
        symbol: '$',
        code: 'TEST',
        emoji: '🇺🇸',
    },
} as const;
